// Package bta implements the Better than Adventure! backend.
//
// BTA is a standalone fork of Minecraft Beta 1.7.3. It is not a Bukkit server:
// there are no plugins, no Chunky and no eula.txt, and it takes no launch
// arguments at all - everything it knows comes from server.properties in its
// working directory. The capabilities it reports say so, and the controller
// hides the features that cannot work rather than offering them and failing.
package bta

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/skipyzi/remindme-homeassistant-addons/minecraft_server/backend/internal/adapter"
	"github.com/skipyzi/remindme-homeassistant-addons/minecraft_server/backend/internal/adapter/javaflags"
)

type Backend struct{}

func New() *Backend { return &Backend{} }

func (b *Backend) Name() string        { return "bta" }
func (b *Backend) DisplayName() string { return "Better than Adventure!" }
func (b *Backend) JarName() string     { return "bta.jar" }

// Capabilities. BTA's world set is a single directory: the other dimensions
// live inside it under `dimensions/`, so unlike Paper there is nothing to list
// separately.
func (b *Backend) Capabilities() adapter.Capabilities {
	return adapter.Capabilities{
		BukkitPlugins:     false,
		BridgeTelemetry:   false,
		TerrainGeneration: false,
		EULAFile:          false,
		ServerPortArg:     false,
		WorldBinding:      adapter.BindLevelLink,
		Dimensions:        []string{"world"},
		Notes: []string{
			"BTA is a fork of Minecraft Beta 1.7.3. Its worlds are in the McRegion format and cannot be opened by a modern server, or the other way round.",
			"There are no Bukkit plugins, so TPS and heap telemetry come from the process rather than from inside the server, and terrain pre-generation is not available.",
			"The listen port is written into server.properties because BTA takes no launch arguments.",
		},
	}
}

func (b *Backend) FlagProfile(profile string, heapMB int) ([]string, error) {
	return javaflags.FlagProfile(profile, heapMB)
}

// Argv builds the JVM command line.
//
// BTA's main method ignores its arguments, so the port and the world are not
// passed here; they are properties. The heap flags are still generated by the
// controller so the limit shown in the UI is the limit in effect.
func (b *Backend) Argv(ctx adapter.LaunchContext) ([]string, error) {
	if ctx.JavaBin == "" {
		return nil, fmt.Errorf("java binary not configured")
	}
	if ctx.JarPath == "" {
		return nil, fmt.Errorf("server JAR not installed")
	}
	if ctx.HeapMaxMB < ctx.HeapMinMB || ctx.HeapMinMB <= 0 {
		return nil, fmt.Errorf("invalid heap configuration %d-%d MB", ctx.HeapMinMB, ctx.HeapMaxMB)
	}
	argv := []string{ctx.JavaBin,
		fmt.Sprintf("-Xms%dM", ctx.HeapMinMB),
		fmt.Sprintf("-Xmx%dM", ctx.HeapMaxMB),
		"-Dfile.encoding=UTF-8",
		"-Djava.awt.headless=true",
	}
	argv = append(argv, ctx.Flags...)
	argv = append(argv, "-jar", ctx.JarPath)
	return argv, nil
}

// WorldArgs is nil: BTA opens the level named by the level-name property inside
// its working directory, so the controller links the active world set there
// instead (adapter.BindLevelLink).
func (b *Backend) WorldArgs(string) []string { return nil }

// Console commands. BTA's console uses Brigadier, so save is one command with
// sub-commands rather than the three hyphenated ones a modern server has.
func (b *Backend) StopCommand() string    { return "stop" }
func (b *Backend) SaveAllCommand() string { return "save all" }
func (b *Backend) SaveOffCommand() string { return "save off" }
func (b *Backend) SaveOnCommand() string  { return "save on" }

// GenerationCommands is empty: no pre-generation plugin exists for BTA.
func (b *Backend) GenerationCommands(adapter.GenerationAction) []string { return nil }

func (b *Backend) PropertiesFile() string { return "server.properties" }

// ConfigFiles. BTA keeps its lists as plain text files, one name per line,
// rather than as the JSON files a modern server uses.
func (b *Backend) ConfigFiles() []adapter.ConfigFile {
	return []adapter.ConfigFile{
		{Name: "server.properties", RelPath: "server.properties", Format: "properties",
			Description: "BTA server settings", RestartRequired: true, CreateIfMissing: true},
		{Name: "ops.txt", RelPath: "ops.txt", Format: "lines",
			Description: "Server operators, one name per line", RestartRequired: false, CreateIfMissing: true},
		{Name: "white-list.txt", RelPath: "white-list.txt", Format: "lines",
			Description: "Whitelisted players, one name per line", RestartRequired: false, CreateIfMissing: true},
		{Name: "banned-players.txt", RelPath: "banned-players.txt", Format: "lines",
			Description: "Banned players", RestartRequired: false, CreateIfMissing: true},
		{Name: "banned-ips.txt", RelPath: "banned-ips.txt", Format: "lines",
			Description: "Banned addresses", RestartRequired: false, CreateIfMissing: true},
	}
}

// DefaultProperties seeds a new installation.
//
// stats-token is deliberately empty: BTA only contacts its stats API when a
// token is set, and nothing here should phone home unless the operator asks for
// it. view-distance is lower than the BTA default because a Beta-era server
// keeps every chunk in the main thread's tick loop.
func (b *Backend) DefaultProperties() map[string]string {
	return map[string]string{
		"level-name":       "world",
		"motd":             "Minecraft on Home Assistant",
		"default-gamemode": "survival",
		"difficulty":       "2",
		"max-players":      "10",
		"view-distance":    "7",
		"online-mode":      "true",
		"white-list":       "false",
		"pvp":              "true",
		"spawn-animals":    "true",
		"spawn-monsters":   "true",
		"spawn-protection": "16",
		"allow-flight":     "false",
		"allow-nether":     "true",
		"allow-paradise":   "true",
		"server-ip":        "",
		"stats-token":      "",
	}
}

// EULAAcceptedContent is unused: BTA has no eula.txt (Capabilities.EULAFile is
// false), so the controller never writes one.
func (b *Backend) EULAAcceptedContent() string { return "" }

// ------------------------------------------------------------ log grammar ----

// BTA logs through log4j with the pattern [HH:mm:ss] [thread/LEVEL]: message.
var (
	// BTA prints the startup time in nanoseconds, not seconds.
	reReady   = regexp.MustCompile(`Done \(\d+ns\)! For help`)
	reJoin    = regexp.MustCompile(`\]:\s*([A-Za-z0-9_]{1,16}) joined the game\.`)
	reLeave   = regexp.MustCompile(`\]:\s*([A-Za-z0-9_]{1,16}) left the game\.`)
	reVersion = regexp.MustCompile(`Starting Better than Adventure! server for version (\S+)`)
	reLevel   = regexp.MustCompile(`Preparing level "([^"]*)"`)
)

// Parse recognises the console lines the controller acts on.
func (b *Backend) Parse(line string) adapter.LogEvent {
	ev := adapter.LogEvent{Kind: adapter.KindOther, Message: line}

	switch {
	case reReady.MatchString(line):
		ev.Kind = adapter.KindReady
		return ev
	case strings.Contains(line, "Stopping the server"):
		ev.Kind = adapter.KindStopping
		return ev
	case strings.Contains(line, "FAILED TO BIND TO PORT"):
		ev.Kind = adapter.KindPortUnavailable
		return ev
	case strings.Contains(line, "java.lang.OutOfMemoryError"), strings.Contains(line, "NOT ENOUGH RAM"):
		ev.Kind = adapter.KindOutOfMemory
		return ev
	case strings.Contains(line, "Saving complete"):
		ev.Kind = adapter.KindSaved
		return ev
	case strings.Contains(line, "Disabling auto saving"):
		ev.Kind = adapter.KindSaveDisabled
		return ev
	case strings.Contains(line, "Enabling auto saving"):
		ev.Kind = adapter.KindSaveEnabled
		return ev
	case strings.Contains(line, "Failed to load level"), strings.Contains(line, "level.dat is corrupt"),
		strings.Contains(line, "Exception instancing ISaveFormat"):
		ev.Kind = adapter.KindWorldCorrupt
		return ev
	}
	if m := reJoin.FindStringSubmatch(line); m != nil {
		ev.Kind, ev.Player = adapter.KindPlayerJoin, m[1]
		return ev
	}
	if m := reLeave.FindStringSubmatch(line); m != nil {
		ev.Kind, ev.Player = adapter.KindPlayerLeave, m[1]
		return ev
	}
	if m := reVersion.FindStringSubmatch(line); m != nil {
		ev.Kind, ev.Version = adapter.KindVersion, m[1]
		return ev
	}
	if m := reLevel.FindStringSubmatch(line); m != nil {
		ev.Kind, ev.World = adapter.KindOther, m[1]
		return ev
	}
	return ev
}

// PortProperty is the server.properties key BTA reads its listen port from. The
// controller writes it because there is no launch argument for it.
const PortProperty = "server-port"

// FormatPort renders a port for the properties file.
func FormatPort(port int) string { return strconv.Itoa(port) }
