// Package paper implements the PaperMC backend: launch arguments, console
// grammar and the set of configuration files Paper owns.
package paper

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/skipyzi/remindme-homeassistant-addons/minecraft_server/backend/internal/adapter"
	"github.com/skipyzi/remindme-homeassistant-addons/minecraft_server/backend/internal/adapter/javaflags"
)

// FlagProfile is kept as a package function because the JVM flag profiles used
// to live here.
var FlagProfile = javaflags.FlagProfile

// FlagProfiles lists the selectable profiles for the UI.
var FlagProfiles = javaflags.FlagProfiles

type Backend struct{}

func New() *Backend { return &Backend{} }

func (b *Backend) Name() string        { return "paper" }
func (b *Backend) DisplayName() string { return "PaperMC" }
func (b *Backend) JarName() string     { return "paper.jar" }

// Capabilities: Paper is the flavour every controller feature was written
// against, so all of them apply.
func (b *Backend) Capabilities() adapter.Capabilities {
	return adapter.Capabilities{
		BukkitPlugins:     true,
		BridgeTelemetry:   true,
		TerrainGeneration: true,
		EULAFile:          true,
		ServerPortArg:     true,
		WorldBinding:      adapter.BindContainerArg,
		ModLoader:         "paper",
		ModDir:            "plugins",
		Dimensions:        []string{"world", "world_nether", "world_the_end"},
	}
}

// FlagProfile resolves a JVM flag profile name.
func (b *Backend) FlagProfile(profile string, heapMB int) ([]string, error) {
	return javaflags.FlagProfile(profile, heapMB)
}

// Argv builds the JVM command line.
//
// Order matters: JVM options first, then -jar, then Paper's own arguments. The
// heap flags are always generated by the controller (custom flags that try to set
// -Xmx are rejected in appcfg.ValidateJavaFlags) so the memory limit shown in the
// UI is always the memory limit in effect.
func (b *Backend) Argv(ctx adapter.LaunchContext) ([]string, error) {
	if ctx.JavaBin == "" {
		return nil, fmt.Errorf("java binary not configured")
	}
	if ctx.JarPath == "" {
		return nil, fmt.Errorf("server JAR not installed")
	}
	if ctx.HeapMaxMB < ctx.HeapMinMB || ctx.HeapMinMB <= 0 {
		return nil, fmt.Errorf("invalid heap configuration %d-%d MB", ctx.HeapMinMB, ctx.HeapMaxMB)
	}
	argv := []string{ctx.JavaBin}
	argv = append(argv,
		fmt.Sprintf("-Xms%dM", ctx.HeapMinMB),
		fmt.Sprintf("-Xmx%dM", ctx.HeapMaxMB),
		"-Dfile.encoding=UTF-8",
		"-Djava.awt.headless=true",
		// Terminal handling: Paper's JLine console fights with a piped stdin.
		"-Dcom.mojang.eula.agree=false",
		"-Dterminal.jline=false",
		"-Dterminal.ansi=false",
	)
	argv = append(argv, ctx.Flags...)
	argv = append(argv, "-jar", ctx.JarPath)
	if ctx.Nogui {
		argv = append(argv, "--nogui")
	}
	if ctx.ServerPort > 0 {
		argv = append(argv, "--port", strconv.Itoa(ctx.ServerPort))
	}
	return argv, nil
}

// WorldArgs returns the Paper arguments that point the server at a world set.
// Switching worlds is therefore a change of launch arguments - no data is moved
// and nothing has to be swapped while the server is stopped.
func (b *Backend) WorldArgs(dir string) []string { return WorldContainerArgs(dir) }

// WorldContainerArgs is the package-level form, kept because it reads better at
// the call sites that build launch arguments.
func WorldContainerArgs(dir string) []string {
	return []string{"--world-container", filepath.ToSlash(dir)}
}

func (b *Backend) StopCommand() string    { return "stop" }
func (b *Backend) SaveAllCommand() string { return "save-all flush" }
func (b *Backend) SaveOffCommand() string { return "save-off" }
func (b *Backend) SaveOnCommand() string  { return "save-on" }

// GenerationCommands maps a generation verb onto Chunky console commands.
func (b *Backend) GenerationCommands(a adapter.GenerationAction) []string {
	switch a.Verb {
	case "configure":
		cmds := []string{}
		if a.World != "" {
			cmds = append(cmds, "chunky world "+a.World)
		}
		cmds = append(cmds,
			fmt.Sprintf("chunky center %d %d", a.CenterX, a.CenterZ),
			"chunky shape "+shapeOrDefault(a.Shape),
			fmt.Sprintf("chunky radius %d", a.Radius),
		)
		return cmds
	case "start":
		return []string{"chunky start"}
	case "pause":
		return []string{"chunky pause"}
	case "resume":
		return []string{"chunky continue"}
	case "cancel":
		return []string{"chunky cancel"}
	case "progress":
		return []string{"chunky progress"}
	case "quiet":
		// Chunky's quiet interval controls how often progress is printed; the
		// controller parses those lines, so a short interval is wanted.
		return []string{"chunky quiet 5"}
	default:
		return nil
	}
}

func shapeOrDefault(s string) string {
	switch s {
	case "square", "circle", "rectangle", "oval", "star", "triangle", "diamond", "pentagon", "hexagon":
		return s
	default:
		return "square"
	}
}

// PropertiesFile is Paper's key/value settings file.
func (b *Backend) PropertiesFile() string { return "server.properties" }

func (b *Backend) ConfigFiles() []adapter.ConfigFile {
	return []adapter.ConfigFile{
		{Name: "server.properties", RelPath: "server.properties", Format: "properties",
			Description: "Vanilla server settings", RestartRequired: true, CreateIfMissing: true},
		{Name: "bukkit.yml", RelPath: "bukkit.yml", Format: "yaml",
			Description: "Bukkit spawn limits and chunk settings", RestartRequired: true},
		{Name: "spigot.yml", RelPath: "spigot.yml", Format: "yaml",
			Description: "Spigot entity activation ranges and view distance", RestartRequired: true},
		{Name: "paper-global.yml", RelPath: "config/paper-global.yml", Format: "yaml",
			Description: "Paper global configuration", RestartRequired: true},
		{Name: "paper-world-defaults.yml", RelPath: "config/paper-world-defaults.yml", Format: "yaml",
			Description: "Paper per-world defaults", RestartRequired: true},
		{Name: "ops.json", RelPath: "ops.json", Format: "json",
			Description: "Server operators", RestartRequired: false, CreateIfMissing: true},
		{Name: "whitelist.json", RelPath: "whitelist.json", Format: "json",
			Description: "Whitelisted players", RestartRequired: false, CreateIfMissing: true},
	}
}

// DefaultProperties seeds a new installation with Raspberry Pi friendly values.
// They are conservative on purpose: view and simulation distance dominate CPU
// and memory use on a Pi far more than any JVM flag.
func (b *Backend) DefaultProperties() map[string]string {
	return map[string]string{
		"level-name":                    "world",
		"motd":                          "Minecraft on Home Assistant",
		"gamemode":                      "survival",
		"difficulty":                    "normal",
		"max-players":                   "10",
		"view-distance":                 "7",
		"simulation-distance":           "5",
		"online-mode":                   "true",
		"white-list":                    "false",
		"pvp":                           "true",
		"enable-command-block":          "false",
		"spawn-protection":              "16",
		"allow-flight":                  "false",
		"enable-rcon":                   "false",
		"sync-chunk-writes":             "false",
		"max-tick-time":                 "60000",
		"network-compression-threshold": "256",
		"enforce-secure-profile":        "true",
	}
}

func (b *Backend) EULAAcceptedContent() string {
	return "# Accepted through the Home Assistant Minecraft add-on management UI.\n" +
		"# See https://aka.ms/MinecraftEULA\n" +
		"eula=true\n"
}

// ------------------------------------------------------------ log grammar ----

var (
	reReady      = regexp.MustCompile(`Done \(([0-9.]+)s\)! For help`)
	reJoin       = regexp.MustCompile(`\]:\s*([A-Za-z0-9_]{1,16}) joined the game`)
	reLeave      = regexp.MustCompile(`\]:\s*([A-Za-z0-9_]{1,16}) left the game`)
	reVersion    = regexp.MustCompile(`Starting minecraft server version ([0-9][^\s]*)`)
	rePaperVer   = regexp.MustCompile(`This server is running ([A-Za-z]+) version ([^\s]+)`)
	rePercent    = regexp.MustCompile(`([0-9]+(?:\.[0-9]+)?)%`)
	reFraction   = regexp.MustCompile(`([0-9]+)\s*/\s*([0-9]+)\s*chunks`)
	reRate       = regexp.MustCompile(`([0-9]+(?:\.[0-9]+)?)\s*(?:cps|chunks/s)`)
	reETA        = regexp.MustCompile(`ETA[:\s]+([0-9]+:[0-9]{2}(?::[0-9]{2})?)`)
	reChunkyName = regexp.MustCompile(`\[Chunky\]\s*(?:\[([^\]]+)\])?`)
)

// Parse recognises the console lines the controller acts on. Anything else is
// KindOther and only ends up in the console history.
func (b *Backend) Parse(line string) adapter.LogEvent {
	ev := adapter.LogEvent{Kind: adapter.KindOther, Message: line}

	if strings.Contains(line, "[Chunky]") || strings.Contains(line, "Chunky") && strings.Contains(line, "Task") {
		return parseChunky(line)
	}

	switch {
	case reReady.MatchString(line):
		ev.Kind = adapter.KindReady
		return ev
	case strings.Contains(line, "Stopping the server"), strings.Contains(line, "Stopping server"):
		ev.Kind = adapter.KindStopping
		return ev
	case strings.Contains(line, "You need to agree to the EULA"):
		ev.Kind = adapter.KindEULARequired
		return ev
	case strings.Contains(line, "FAILED TO BIND TO PORT"):
		ev.Kind = adapter.KindPortUnavailable
		return ev
	case strings.Contains(line, "java.lang.OutOfMemoryError"):
		ev.Kind = adapter.KindOutOfMemory
		return ev
	case strings.Contains(line, "Saved the game"), strings.Contains(line, "Saved the world"):
		ev.Kind = adapter.KindSaved
		return ev
	case strings.Contains(line, "Automatic saving is now disabled"), strings.Contains(line, "Turned off world auto-saving"):
		ev.Kind = adapter.KindSaveDisabled
		return ev
	case strings.Contains(line, "Automatic saving is now enabled"), strings.Contains(line, "Turned on world auto-saving"):
		ev.Kind = adapter.KindSaveEnabled
		return ev
	case strings.Contains(line, "Unknown command") && strings.Contains(strings.ToLower(line), "chunky"):
		ev.Kind = adapter.KindGenNotInstalled
		return ev
	case strings.Contains(line, "Could not load 'plugins"), strings.Contains(line, "Unsupported API version"),
		strings.Contains(line, "was compiled against an incompatible"):
		ev.Kind = adapter.KindPluginIncompat
		return ev
	case strings.Contains(line, "Chunk file at"), strings.Contains(line, "level.dat is corrupt"),
		strings.Contains(line, "Failed to load level"):
		ev.Kind = adapter.KindWorldCorrupt
		return ev
	}
	if m := reJoin.FindStringSubmatch(line); m != nil {
		ev.Kind, ev.Player = adapter.KindPlayerJoin, m[1]
		return ev
	}
	if m := reLeave.FindStringSubmatch(line); m != nil {
		ev.Kind, ev.Player = adapter.KindPlayerLeave, m[1]
		return ev
	}
	if m := reVersion.FindStringSubmatch(line); m != nil {
		ev.Kind, ev.Version = adapter.KindVersion, m[1]
		return ev
	}
	if m := rePaperVer.FindStringSubmatch(line); m != nil {
		ev.Kind, ev.Build = adapter.KindVersion, m[2]
		return ev
	}
	return ev
}

// parseChunky is intentionally tolerant: Chunky's progress format has changed
// between releases, so the parser looks for the individual numbers rather than
// matching one exact sentence.
func parseChunky(line string) adapter.LogEvent {
	ev := adapter.LogEvent{Kind: adapter.KindGenProgress, Message: line}
	if m := reChunkyName.FindStringSubmatch(line); len(m) > 1 {
		ev.World = m[1]
	}
	lower := strings.ToLower(line)
	switch {
	case strings.Contains(lower, "task finished"), strings.Contains(lower, "task complete"),
		strings.Contains(lower, "finished for"), strings.Contains(lower, "100.00%"):
		ev.Kind = adapter.KindGenTaskDone
	case strings.Contains(lower, "task cancelled"), strings.Contains(lower, "task canceled"),
		strings.Contains(lower, "task stopped"):
		ev.Kind = adapter.KindGenTaskCancelled
	case strings.Contains(lower, "task started"), strings.Contains(lower, "starting task"):
		ev.Kind = adapter.KindGenTaskStarted
	}
	if m := rePercent.FindStringSubmatch(line); m != nil {
		ev.Percent, _ = strconv.ParseFloat(m[1], 64)
	}
	if m := reFraction.FindStringSubmatch(line); m != nil {
		ev.ChunksDone, _ = strconv.ParseInt(m[1], 10, 64)
		ev.ChunksTotal, _ = strconv.ParseInt(m[2], 10, 64)
	}
	if m := reRate.FindStringSubmatch(line); m != nil {
		ev.Rate, _ = strconv.ParseFloat(m[1], 64)
	}
	if m := reETA.FindStringSubmatch(line); m != nil {
		ev.ETASeconds = parseClockDuration(m[1])
	}
	return ev
}

func parseClockDuration(v string) int64 {
	parts := strings.Split(v, ":")
	var total int64
	for _, p := range parts {
		n, err := strconv.ParseInt(p, 10, 64)
		if err != nil {
			return 0
		}
		total = total*60 + n
	}
	return total
}
